In [30]:
import numpy as np
from IPython.core.display import HTML

In [8]:
x = np.array([1,2,3]) # 1D vector
print(x.shape)
x

(3,)


array([1, 2, 3])

In [12]:
y = x.reshape(-1,1) # vertical 2D vector
y

array([[1],
       [2],
       [3]])

In [22]:
z = x.reshape(1,-1) # horiz 2D vector
print(z)
z.shape

[[1 2 3]]
<class 'numpy.ndarray'>


(1, 3)

In [27]:
YELLOW = "#fefecd" # "#fbfbd0" # "#FBFEB0"
BLUE = "#D9E6F5"
GREEN = "#cfe2d4"
class Prefs: pass
prefs = Prefs()
prefs.max_str_len = 20         # how many chars before we abbreviate with ...?
prefs.max_horiz_array_len = 40 # how many chars before it's too wide and we go vertical?
prefs.max_list_elems = 10      # how many elements max to display in list (unused so far)

In [25]:
def ndarrayviz(data):
    
    return None

def gr_ndarray_html(elems, title=None, bgcolor=YELLOW):
    if len(elems)==0:
        return " "
    header = '<table BORDER="0" CELLPADDING="0" CELLBORDER="1" CELLSPACING="0">\n'
    tail = "</table>\n"
    blankrow = '<tr><td colspan="3" cellpadding="1" border="0" bgcolor="%s"></td></tr>' % (bgcolor)
    sep = '<td cellspacing="0" cellpadding="0" border="0"></td>'

    rows = []
    if title is not None:
        title = '<tr><td cellspacing="0" colspan="3" cellpadding="0" bgcolor="%s" border="1" sides="b" align="center"><font color="#444443" FACE="Times-Italic" point-size="11">%s</font></td></tr>\n' % (bgcolor, title)
        rows.append(title)

    N = len(elems)
    if N > prefs.max_list_elems:
        items = [(i,elems[i]) for i in range(prefs.max_list_elems-1)] + [(Ellipsis(),Ellipsis()),(N-1,elems[N - 1])]
    else:
        items = [(i,elems[i]) for i in range(N)]

    if len(items)>0:
        for i,e in items:
            if len(str(e)) > prefs.max_str_len:
                e = abbrev_and_escape(str(e))
            v = repr(e)
            value = '<td port="%s" cellspacing="0" cellpadding="1" bgcolor="%s" border="0" align="center"><font color="#444443" point-size="11"> %s</font></td>\n' % (i, bgcolor, v)
            row = '<tr>' + value + '</tr>\n'
            rows.append(row)
    else:
        rows.append('<tr><td cellspacing="0" cellpadding="0" border="0"><font point-size="9"> ... </font></td></tr>\n')

    return header + blankrow.join(rows) + tail

In [33]:
HTML(gr_ndarray_html(z))